import turtle
tracey = turtle
tracey.penup()
tracey.backward(475)
tracey.right(90)
tracey.forward(475)
tracey.left(90)
tracey.forward(237.5)
tracey.left(90)
tracey.pendown()
tracey.forward(950)
tracey.penup()
tracey.right(90)
tracey.forward(237.5)
tracey.right(90)
tracey.pendown()
tracey.forward(950)
tracey.penup()
tracey.left(90)
tracey.forward(237.5)
tracey.left(90)
tracey.pendown()
tracey.forward(950)
tracey.penup()